import { State } from './state.js';
import { degPerMm, MOTOR_MAX_DEG_S } from './math.js';

// Builds the PATH table + a self-contained SPIKE Prime (App 3) Python program.
// Robot tracks its own field position from wheel encoders (+ gyro yaw),
// so per-segment speed, ramps and stops all come from State.plan.
export function generateCode(){
  const plan = State.plan;
  const rows = [];
  let start = { x: 0, y: 0 };

  if(plan && plan.pts.length > 1){
    const P = plan.pts;
    start = P[0];
    let lastS = 0;
    for(let i = 1; i < P.length; i++){
      const p = P[i];
      const isLast = i === P.length - 1;
      const isStop = p.stopMs > 0;
      if(!isStop && !isLast && p.s - lastS < 20) continue;   // ~20 mm spacing
      lastS = p.s;
      let mode = 0, arg = 0;
      if(p.action){ mode = 2; arg = p.action; }
      else if(isStop || isLast){ mode = 1; arg = p.stopMs > 1 ? Math.round(p.stopMs) : 0; }
      rows.push(`    (${Math.round(p.x)}, ${Math.round(p.y)}, ${Math.round(p.v)}, ${mode}, ${arg}),`
        + (mode === 2 ? `  # ★${arg}` : mode === 1 && arg ? `  # pause ${arg} ms` : ''));
    }
  }

  const dpm = degPerMm();
  const pathOnly = [
    `START = (${Math.round(start.x)}, ${Math.round(start.y)})`,
    '# (x_mm, y_mm, speed_mm_s, mode, arg)   mode: 0=pass  1=stop(arg=pause ms)  2=action(arg=no.)',
    'PATH = [',
    rows.length ? rows.join('\n') : '    # (draw curves, then click them in Select mode to build a route)',
    ']'
  ].join('\n');

  const est = plan && plan.time ? (plan.time / 1000).toFixed(1) + ' s' : '-';
  const fullCode = `# Generated by Ground Station  (Sancha-Claus Tech)
# 2-Motor Omni (+-Drive) -- LEGO SPIKE Prime (SPIKE App 3 Python)
# Field: 1143 x 2362 mm (FLL), origin = bottom-left
# Route length ${plan ? Math.round(plan.total) : 0} mm, estimated time ${est}

from hub import port, motion_sensor
import motor
import time
import math

# ── Robot preferences (from Ground Station) ──────────────
PORT_X = port.${State.prefPortX.toUpperCase()}      # motor that moves the robot left/right
PORT_Y = port.${State.prefPortY.toUpperCase()}      # motor that moves the robot forward/back
DPM_X = ${dpm.x.toFixed(4)}   # motor degrees per mm (wheel, gear, calibration)
DPM_Y = ${dpm.y.toFixed(4)}
INV_X = ${State.prefInvertX ? -1 : 1}          # set -1 if +degrees moves the robot LEFT
INV_Y = ${State.prefInvertY ? -1 : 1}          # set -1 if +degrees moves the robot BACKWARD
BACKLASH = ${State.prefBacklash | 0}       # gear play in motor degrees
HEADING = ${State.robotHeading | 0}        # robot facing on the field (deg, clockwise from +Y)
USE_GYRO = ${State.prefUseGyro ? 'True' : 'False'}
GYRO_SIGN = -1     # SPIKE yaw is +counter-clockwise; flip to 1 if correction goes the wrong way

# ── Tuning ───────────────────────────────────────────────
ACCEL = ${Math.round(State.prefAccel)}        # mm/s^2  max change of commanded speed
MAX_DEG_S = ${MOTOR_MAX_DEG_S}    # motor speed limit
LOOKAHEAD = 25     # mm  pass-through points are skipped inside this radius
STOP_TOL = 4       # mm  "arrived" radius for stop points
STOP_TIMEOUT = 1500  # ms  give up settling after this
KP_STOP = 3.0      # (mm/s)/mm  approach gain near stop points
MIN_STOP_SPEED = 15  # mm/s

${pathOnly}


def run_action(n):
    # Write your mission actions here, e.g.
    # if n == 1: motor.run_for_degrees(port.C, 180, 500)
    pass


def _bl(raw, w):
    # backlash model: wheel follows motor with BACKLASH degrees of play
    h = BACKLASH / 2
    if raw - w > h:
        return raw - h
    if w - raw > h:
        return raw + h
    return w


class Odometry:
    def __init__(self, x, y):
        motor.reset_relative_position(PORT_X, 0)
        motor.reset_relative_position(PORT_Y, 0)
        if USE_GYRO:
            motion_sensor.reset_yaw(0)
        self.wx = 0
        self.wy = 0
        self.x = x
        self.y = y

    def yaw(self):
        if not USE_GYRO:
            return 0
        return GYRO_SIGN * motion_sensor.tilt_angles()[0] / 10

    def update(self):
        wx = _bl(motor.relative_position(PORT_X) * INV_X, self.wx)
        wy = _bl(motor.relative_position(PORT_Y) * INV_Y, self.wy)
        lx = (wx - self.wx) / DPM_X     # robot-local mm (right)
        ly = (wy - self.wy) / DPM_Y     # robot-local mm (forward)
        self.wx, self.wy = wx, wy
        h = math.radians(HEADING + self.yaw())
        c, s = math.cos(h), math.sin(h)
        self.x += lx * c + ly * s
        self.y += -lx * s + ly * c
        return h


def drive(vx, vy, h):
    # field velocity (mm/s) -> motor speeds (deg/s), using the real heading h
    c, s = math.cos(h), math.sin(h)
    lx = vx * c - vy * s
    ly = vx * s + vy * c
    dx = lx * DPM_X * INV_X
    dy = ly * DPM_Y * INV_Y
    m = max(abs(dx), abs(dy))
    if m > MAX_DEG_S:
        dx = dx * MAX_DEG_S / m
        dy = dy * MAX_DEG_S / m
    motor.run(PORT_X, int(dx))
    motor.run(PORT_Y, int(dy))


def halt():
    motor.stop(PORT_X)
    motor.stop(PORT_Y)


def follow():
    odo = Odometry(START[0], START[1])
    vx = vy = 0.0
    last_v = 0
    i = 0
    n = len(PATH)
    settle_t = None
    t_prev = time.ticks_ms()
    while i < n:
        tx, ty, v, mode, arg = PATH[i]
        h = odo.update()
        ex = tx - odo.x
        ey = ty - odo.y
        d = math.sqrt(ex * ex + ey * ey)
        now = time.ticks_ms()

        if mode == 0:
            if d < LOOKAHEAD and i < n - 1:
                i += 1
                last_v = v
                continue
            spd = v
        else:
            if d < LOOKAHEAD and settle_t is None:
                settle_t = now
            done = d < STOP_TOL or (settle_t is not None and time.ticks_diff(now, settle_t) > STOP_TIMEOUT)
            if done:
                halt()
                vx = vy = 0.0
                if mode == 2:
                    run_action(arg)
                elif arg > 0:
                    time.sleep_ms(arg)
                odo.update()
                i += 1
                settle_t = None
                t_prev = time.ticks_ms()
                continue
            spd = max(MIN_STOP_SPEED, min(max(v, last_v), KP_STOP * d))

        if d > 0.01:
            want_x = ex / d * spd
            want_y = ey / d * spd
        else:
            want_x = want_y = 0.0
        dt = time.ticks_diff(now, t_prev) / 1000
        t_prev = now
        dv = ACCEL * dt
        vx += max(-dv, min(dv, want_x - vx))
        vy += max(-dv, min(dv, want_y - vy))
        drive(vx, vy, h)
        time.sleep_ms(5)
    halt()


follow()
`;
  return { fullCode, pathOnly };
}
